<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'About' => 'אודות',
  'Account' => 'חשבון',
  'Account Name' => 'שם חשבון',
  'Account Template' => 'תבנית חשבון',
  'Account Types' => 'סוג חשבון',
  'Account id' => 'מזהה חשבון',
  'Accounts' => 'חשבונות',
  'Acct. balance' => 'מאזן חשבון',
  'Accts. recon.' => 'התאמת חשבונות',
  'All current compnay data will be removed:' => 'כל המידע בחברה הנוכחית יוסר',		//All current company
  'Backup restore' => 'שחזור גיבוי',
  'Bag Report' => 'דיווח באגים',							//Bug Report
  'Balance' => 'מאזן',
  'Bank deposits' => 'הפקדות בנק',
  'Bank docs entry' => 'ייבוא דפי חשבון בנק',
  'Bank recon.' => 'התאמת בנקים',
  'Bankbooks' => 'חשבון בנק',
  'Business docs' => 'מסמכים עסקיים',
  'Bussines details' => 'פרטי בית העסק',						//Business Details
  'Cant find Company template file unable to create database' => 'לא מוצא קובץ תבנית חברה ולכן לא יכול ליצור מסד נתונים',
  'Categories' => 'קטגוריות',
  'Change Company' => 'שנה חברה',
  'Change language' => 'שנה שפה',
  'Chose Account' => 'בחר חשבון',							//Choose
  'Chose Bank' => 'בחר בנק',							//Choose
  'Chose Payment type' => 'בחר סוג אמצעי תשלום',					//Choose
  'Comments' => 'הערות',
  'Contact Item' => 'פרטי קשר',
  'Costum Fields' => 'שדות מותאמים',						//Custom
  'Create' => 'צור',
  'Create AccTemplate' => 'צור תבנית חשבון',
  'Create Account Type' => 'צור סוג חשבון',
  'Create Company' => 'צור חברה',
  'Create Currency Rate' => 'צור שער חליפין',
  'Create Item Tax Catagory' => 'צור קטגורית מס לפריטים',				//Create Item Tax Category
  'Create Item Units' => 'צור יחידת מידה לפריטים',
  'Create Manual Transaction' => 'צור תנועה ידנית',
  'Create Open Balance' => 'צור תנועה מאזנת',						
  'Create User' => 'צור משתמש',
  'Credit inv.' => 'חשבונית זיכוי',
  'Currency' => 'מטבע',
  'Currency rates' => 'שער מטבע',
  'Customers owes' => 'חוב לקוח',							//Customers in Debit
  'Customers owing money' => 'לקוחות חייבים',						//Customers in Debit
  'Delete User' => 'מחק משתמש',
  'Delivery doc.' => 'תעודת משלוח',
  'Deposit Success' => 'הפקדה הצליחה',
  'Description' => 'תיאור',
  'Display transactions' => 'הצג תנועות יומן',
  'Doc. Issued date' => 'תאריך הפקת מסמך',
  'Due date' => 'תאריך תוקף',
  'Email' => 'דוא"ל',
  'Error' => 'שגיאה',
  'From Date' => 'מתאריך',
  'General backup' => 'גיבוי כללי',
  'ID' => 'מזהה',
  'Import Export' => 'ייבוא יצוא',
  'In Out' => 'הכנסות הוצאות',							//Credit Debit
  'Income' => 'הכנסות',
  'Income outcome' => 'הכנסות הוצאות',						//Credit Debit
  'Income tax advances' => 'מקדמות מס הכנסה',
  'Invoice' => 'חשבונית מס',
  'Invoice receipt' => 'חשבונית מס קבלה',
  'Item Template' => 'תבנית פריט',
  'Item id' => 'מזהה פריט',
  'Items' => 'פריטים',
  'Line' => 'שורה',
  'List User' => 'הצג משתמש',
  'List Users' => 'הצג משתמשים',
  'Login' => 'התחבר',
  0 => '',
  'Logout' => 'התנתק',
  'Mach Success' => 'התאמה הצליחה',
  'Mach1 Success' => 'התאמה 1 הצליחה',
  'Mach2 Success' => 'התאמה 2 הצליחה',
  'Manage Bankbooks' => 'נהל דפי בנק',
  'Manage Currencies Rates' => 'נהל שערי מטבע',
  'Manage Customers' => 'נהל לקוחות',
  'Manage Documenet types' => 'נהל סוגי מסמכים',
  'Manage Eav Fields' => 'נהל שדות',
  'Manage Groups' => 'נהל קבוצות',
  'Manage Item Categories' => 'נהל קטגוריות פריטים',
  'Manage Item Tax Catagories' => 'נהל קטגוריות מס לפריטים',
  'Manage Suppliers' => 'נהל ספקים',
  'Manage Users' => 'נהל משתמשים',
  'Manual Journal Voucher' => 'תנועת יומן ידנית',
  'Monthly Prof. & loss' => 'דוח רווח -הפסד חודשי',
  'Name' => 'שם',
  'Nat. Ins. payment' => 'תשלום ביטוח לאומי',
  'New' => 'חדש',
  'No.' => 'מס\'',
  'Open Format Create' => 'צור קובץ אחיד',
  'Open docs' => 'פתח מסמכים',
  'Open docs Import' => 'יבוא קובץ אחיד',
  'Opening Balance' => 'פתיחת מאזן',
  'Openning balances' => 'פתיחת מאזנים',
  'Outcome' => 'הוצאות',
  'PCN874' => 'PCN874',
  'PCN874 Report' => 'דוח PCN874',
  'PDF' => '',
  'Paid Support' => 'תמיכה בתשלום',
  'Parchace Order' => 'הזמנת רכש',							//Purchase Order
  'Password' => 'סיסמא',
  'Payment' => 'תשלום',
  'Prefix' => 'קידומת',
  'Preview' => 'תצוגה מקדימה',
  'Price' => 'מחיר',
  'Print' => 'הדפסה',
  'Print docs.' => 'הדפסת מסמכים',
  'Profit & loss' => 'רווח הפסד',
  'Proforma' => 'חשבונית עסקה',
  'Qty.' => 'כמות',
  'Quote' => 'הצעת מחיר',
  'Receipt' => 'קבלה',
  'Reconciliations' => 'התאמות',
  'Register' => 'קופה',
  'Remember me next time' => 'זכור אותי לפעם הבאה',
  'Remove' => 'הסר',
  'Reports' => 'דוחות',
  'Restore Backup From File' => 'שחזר מקובץ גיבוי',
  'Return doc.' => 'תעודת החזרה',
  'Sales Order' => 'הזמנת מכירות',
  'Search' => 'חפש',
  'Select Company' => 'בחר חברה',
  'Select year' => 'בחר שנה',
  'Settings' => 'הגדרות',
  'Show bank recon.' => 'הצג התאמות בנק',
  'Show recon.' => 'הצג התאמות',
  'Stock' => 'מלאי',
  'String' => 'מחרוזת',
  'Subtotal tax excluded' => 'סה"כ מס שנוסף',
  'Subtotal tax exempt' => 'סה"כ מס שהופחת',
  'Subtotal to pay' => 'סה"כ לתשלום',
  'Support' => 'תמיכה',
  'Tax Catagory' => 'קטגורית מס',							//Tax Category
  'Tax Catagory For Items' => 'קטגורית מס לפריטים',					//Tax Category For Items			
  'Tax Report' => 'דוח מע"מ',
  'To' => 'אל',
  'To Date' => 'לתאריך',
  'Total' => 'סה"כ',
  'Transactions' => 'תנועות',
  'Unit' => 'יחידה',
  'Units' => 'יחידות',
  'Unt. Price' => 'מחיר יחידה',
  'Update' => 'עדכן',
  'Update Account Template #' => 'עדכן תבנית חשבון',
  'Update Configuration' => 'עדכן הגדרות',
  'Update Item Tax Catagory #' => 'עדכן קטגורית מס לפריט',
  'Update Item Unit' => 'עדכן יחידת מידה לפריט',
  'Update User' => 'עדכן משתמש',
  'Upload' => 'טען',
  'Username' => 'שם משתמש',
  'VAT' => 'מע"מ',
  'VAT No.' => 'מספר עוסק מורשה/ח"פ',
  'VAT calculation' => 'חישוב מע"מ',
  'VAT payment' => 'תשלום מע"מ',
  'Vat No.' => 'מספר עוסק מורשה/ח"פ',
  'Vat Report' => 'דוח מע"מ',
  'View Document ' => 'צפה במסמך',
  'View Item Tax Catagory #' => 'צפה קטוגרית מס לפריט',					//View Item Tax Category
  'View User ' => 'צפה במשתמש',
  'Werehouses' => 'מחסנים',							//Warehouses
  'Worrinng:' => 'אזהרה',								//Warning
  'balance' => 'מאזן',
  'insert Asstes outcome' => 'קליטת רכוש קבוע',					//Insert Assets outcome
  'insert Buisness outcome' => 'קליטת הוצאה עסקית',					//Insert Business outcome
  'message to be translated' => 'הודעה לתרגום',
  'tax' => 'מס',
  'vat' => 'מע"מ',
 

  'company.acc.assetvat' => '',
  'company.acc.buyvat' => '',
  'company.acc.custtax' => '',
  'company.acc.irs' => '',
  'company.acc.natinspay' => '',
  'company.acc.openbalance' => '',
  'company.acc.payvat' => '',
  'company.acc.pretax' => '',
  'company.acc.sellvat' => '',
  'company.address' => 'כתובת',
  'company.city' => 'עיר',
  'company.cur' => 'מטבע עיקרי לחברה',
  'company.logo' => 'לוגו',
  'company.name' => 'שם',
  'company.path' => 'נתיב ליישום',
  'company.pdfprint' => 'הדפס מסמכים ל-PDF',
  'company.seccur' => ' מטבע משני לחברה',
  'company.stock' => 'סוג מלאי',
  'company.tax.rate' => 'שיעור מס',
  'company.transaction' => '',
  'company.vat.id' => '',
  'company.vat.type' => '',
  'company.zip' => 'מיקוד',
  'paypal.apiLive' => 'API של PAY PAL',
  'paypal.apiPassword' => 'סיסמת PAYPAL ל-API',
  'paypal.apiSignature' => 'חתימת PAYPAL ל-API',
  'paypal.apiUsername' => 'משתמש PAYPAL ל-API',
  'server.checkTime' => '',
  'server.dbVersion' => '',
  'server.Latest' => '',
  'server.Version' => '',
  'server.wkhtmltopdf' => '',
  'system.auth' => '',
  'system.name' => '',
  'system.vendor.name' => '',
  'system.vendor.vatnum' => '',
  'system.version' => '',

  
  
  
);
