<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Account' => 'Account',
  'Account Name' => 'Account Name',
  'Account id' => 'Account id',
  'Accounts' => 'Accounts',
  'Accounts Related events' => 'Accounts Related events',
  'Acct. balance' => 'Acct. balance',
  'Add User' => 'Add User',
  'Admin' => 'Admin',
  'Werehouses' => 'Werehouses',
  'company.acc.assetvat' => '',
  'company.acc.buyvat' => '',
  'company.acc.custtax' => '',
  'company.acc.irs' => '',
  'company.acc.natinspay' => '',
  'company.acc.openbalance' => '',
  'company.acc.payvat' => '',
  'company.acc.pretax' => '',
  'company.acc.sellvat' => '',
  'company.address' => 'Address',
  'company.city' => 'City',
  'company.cur' => 'Lead Courrency',
  'company.logo' => 'Logo',
  'company.name' => 'Name',
  'company.path' => 'Applaction Path',
  'company.pdfprint' => 'Print Documents to pdf',
  'company.seccur' => 'Secendory Courrency',
  'company.stock' => 'Stock Type',
  'company.tax.rate' => 'Tax Rate',
  'company.transaction' => '',
  'company.vat.id' => '',
  'company.vat.type' => '',
  'company.zip' => 'ZIP COde',
  'insert Asstes outcome' => '',
  'insert Buisness outcome' => '',
  'message to be translated' => '',
  'paypal.apiLive' => 'PayPal API Live',
  'paypal.apiPassword' => 'PayPal API Password',
  'paypal.apiSignature' => 'PayPal API Signature',
  'paypal.apiUsername' => 'PayPal API User',
  'server.Latest' => '',
  'server.Version' => '',
  'server.checkTime' => '',
  'server.dbVersion' => '',
  'server.wkhtmltopdf' => '',
  'system.auth' => '',
  'system.name' => '',
  'system.vendor.name' => '',
  'system.vendor.vatnum' => '',
  'system.version' => '',
  'no stock' => 'Non Stock Item',
  'Detailes' => 'Details',
  'cheque_num' => 'Check No.',
  'bank' => 'Bank ID',
  'branch' => 'Branch ID',
  'cheque_acct' => 'Account No.',
  'cheque_date' => 'Due Date',
  'card_no' => 'Card No.',
  'pid' => 'Person ID',
  'valid_month' => 'Expiry Month',
  'valid_year' => 'Expiry Year',
  'cvv' => 'CVV',
  'refnum' => 'Reference No.',
  'account_id' => 'Receiving Bank Account',
  'bank_acc' => 'Sending Bank Account',
  'due_date' => 'Transfer Date',
  'last_4_digits' => 'Credit Card Last 4 Digits',
  'firstPymnt' => 'First Payment Sum',
  'paymentsNo' => 'Number of Payments',
  'Print Docs.' => 'Manage Docs.',
  'invoiceReport' => 'Invoices to Collect',
  'outcomeReport' => 'Payments to Suppliers',
  'chequeReport' => 'Income&Expense Chart',
  'accReport' => 'Events For Accounts',
  'salesReport' => 'Pending Sales Orders',
  'docReport' => 'Pending Documents',
  
);
