<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 *
 * @version $Id: $
 */
return array (
  'Account' => '',
  'Address' => '',
  'Ammount' => '',
  'Bank' => '',
  'Bank Refnum' => '',
  'Branch' => '',
  'Category' => '',
  'Certifcate Password' => '',
  'Cheque Account' => '',
  'Cheque Date' => '',
  'Cheque No.' => '',
  'City' => '',
  'Code' => '',
  'Comments' => '',
  'Company' => '',
  'Cookie' => '',
  'Credit Company' => '',
  'Creditcompany' => '',
  'Currency' => '',
  'Date' => '',
  'Dep Date' => '',
  'Description' => '',
  'Doc' => '',
  'Documenet No.' => '',
  'Documenet Type' => '',
  'Due Date' => '',
  'Email' => '',
  'Extrnal No.' => '',
  'First Name' => '',
  'Hash' => '',
  'ID' => '',
  'Idcode' => '',
  'Is Product' => '',
  'Issue Date' => '',
  'Item' => '',
  'Item VAT Catagory' => '',
  'Last Login' => '',
  'Last Name' => '',
  'Line' => '',
  'Manufacturer' => '',
  'Name' => '',
  'No VAT Total' => '',
  'Open Format' => '',
  'Owner' => '',
  'Parent Item' => '',
  'Password' => '',
  'Picture' => '',
  'Price' => '',
  'Printed' => '',
  'Profit' => '',
  'Purchase Price' => '',
  'Qty' => '',
  'Refernce No.' => '',
  'Refnum' => '',
  'Sale Price' => '',
  'Salt' => '',
  'Sescription' => '',
  'Src Tax' => '',
  'Status' => '',
  'Stock Type' => '',
  'Sub Total' => '',
  'Sum' => '',
  'Symbol' => '',
  'Total' => '',
  'Type' => '',
  'Unit' => '',
  'Unit Price' => '',
  'User Name' => '',
  'VAT' => '',
  'VAT No.' => '',
  'Value' => '',
  'Zip' => '',
  'invoice Price' => '',
);
